---
name: Terraform Validation

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.2"
      - name: Terraform fmt
        run: task fmt:check
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.31.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yml
          exit-code: '1'

