name: Bump version
on:
  push:
    branches:
      - hbaker/tag-on-merge

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          TAG_PREFIX: 'v'
