---
name: Lambda Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  lambda-unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          pip install -r scripts/tests/test-requirements.txt
      - name: Run Unit Tests
        run: |
          export AWS_DEFAULT_REGION=us-east-1
          pytest scripts/tests \
            --junitxml=test-results/junit.xml \
            --cov=scripts/tests \
            --cov-report=xml:test-results/coverage.xml
      - name: Upload pytest results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: test-results
          retention-days: 1